/**
 * Aura investor storyboard landing page.
 * Statistics sourced from:
 *   - McKinsey Health Institute (2025) — investing-in-the-future report
 *   - WHO Mental Health Fact Sheet (2025)
 *   - Deloitte Mental Health Wellbeing Industry (2024)
 *
 * Background images: generated by generate_landing_images.py (Gemini "Nano Banana" / imagen-3)
 * If an image hasn't been generated yet, a gradient placeholder is shown instead.
 */
import { AnimatePresence, motion, useInView, useScroll, useTransform } from "framer-motion";
import {
  ArrowRight,
  Brain,
  CheckCircle2,
  Heart,
  Shield,
  Sparkles,
  TrendingUp,
  Zap,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import NeuralCanvas from "../components/landing/NeuralCanvas";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function useCountUp(target: number, decimals = 0) {
  const [val, setVal] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true });
  useEffect(() => {
    if (!inView) return;
    const duration = 1800;
    const step = 16;
    const increments = duration / step;
    const delta = target / increments;
    let cur = 0;
    const id = setInterval(() => {
      cur = Math.min(cur + delta, target);
      setVal(parseFloat(cur.toFixed(decimals)));
      if (cur >= target) clearInterval(id);
    }, step);
    return () => clearInterval(id);
  }, [inView, target, decimals]);
  return { val, ref };
}

function Stat({
  value,
  suffix = "",
  prefix = "",
  label,
  source,
  color = "text-white",
  decimals = 0,
}: {
  value: number;
  suffix?: string;
  prefix?: string;
  label: string;
  source: string;
  color?: string;
  decimals?: number;
}) {
  const { val, ref } = useCountUp(value, decimals);
  return (
    <div className="flex flex-col gap-1">
      <span ref={ref} className={`text-4xl md:text-5xl font-bold tabular-nums ${color}`}>
        {prefix}{decimals > 0 ? val.toFixed(decimals) : val.toLocaleString()}{suffix}
      </span>
      <p className="text-sm text-white/55 leading-relaxed max-w-[16rem]">{label}</p>
      <p className="text-xs text-white/25 italic">{source}</p>
    </div>
  );
}

// Philosopher pull-quote
function Quote({
  text,
  author,
  work,
  accent = "indigo",
}: {
  text: string;
  author: string;
  work: string;
  accent?: "indigo" | "emerald" | "violet" | "rose" | "amber";
}) {
  const bar: Record<string, string> = {
    indigo: "border-indigo-400",
    emerald: "border-emerald-400",
    violet: "border-violet-400",
    rose: "border-rose-400",
    amber: "border-amber-400",
  };
  const txt: Record<string, string> = {
    indigo: "text-indigo-300",
    emerald: "text-emerald-300",
    violet: "text-violet-300",
    rose: "text-rose-300",
    amber: "text-amber-300",
  };
  return (
    <blockquote className={`border-l-[2px] pl-6 py-1 ${bar[accent]}`}>
      <p className="text-xl md:text-2xl italic font-light text-white/85 leading-relaxed tracking-wide">
        &ldquo;{text}&rdquo;
      </p>
      <footer className={`mt-3 text-xs tracking-widest uppercase font-semibold ${txt[accent]}`}>
        — {author}
        {work && <span className="text-white/30 normal-case font-normal tracking-normal ml-2 text-xs">{work}</span>}
      </footer>
    </blockquote>
  );
}

// Section wrapper with scroll-triggered reveal
function Section({
  id,
  children,
  className = "",
}: {
  id: string;
  children: React.ReactNode;
  className?: string;
}) {
  const ref = useRef<HTMLElement>(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <section id={id} ref={ref} className={`relative min-h-screen flex flex-col justify-center px-6 md:px-16 lg:px-28 py-28 ${className}`}>
      <motion.div
        initial={{ opacity: 0, y: 52 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.95, ease: [0.22, 1, 0.36, 1] }}
      >
        {children}
      </motion.div>
    </section>
  );
}

// Section label
function Label({ tag }: { n?: string; tag: string }) {
  return (
    <div className="flex items-center gap-3 mb-10">
      <div className="h-px w-8 bg-white/10" />
      <span className="text-[11px] uppercase tracking-[0.18em] text-white/25">{tag}</span>
    </div>
  );
}

// AI image with gradient fallback
function LandingImage({
  src,
  alt,
  className = "",
  fallback = "from-indigo-900/60 to-violet-900/60",
}: {
  src: string;
  alt: string;
  className?: string;
  fallback?: string;
}) {
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState(false);
  return (
    <div className={`relative overflow-hidden rounded-2xl ${className}`}>
      {!error && (
        <img
          src={src}
          alt={alt}
          className={`w-full h-full object-cover transition-opacity duration-700 ${loaded ? "opacity-100" : "opacity-0"}`}
          onLoad={() => setLoaded(true)}
          onError={() => setError(true)}
        />
      )}
      {(!loaded || error) && (
        <div className={`absolute inset-0 bg-gradient-to-br ${fallback}`} />
      )}
    </div>
  );
}

// Feature card
function Feature({
  icon: Icon,
  title,
  body,
  i = 0,
}: {
  icon: React.ElementType;
  title: string;
  body: string;
  i?: number;
}) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 20 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ delay: i * 0.08, duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
      className="group bg-white/4 hover:bg-white/7 border border-white/8 rounded-2xl p-6 transition-all duration-300"
    >
      <div className="w-9 h-9 rounded-xl bg-indigo-500/20 group-hover:bg-indigo-500/30 flex items-center justify-center mb-4 transition">
        <Icon className="h-4.5 w-4.5 text-indigo-300" />
      </div>
      <h3 className="font-semibold text-white mb-1.5 text-[15px]">{title}</h3>
      <p className="text-sm text-white/45 leading-relaxed">{body}</p>
    </motion.div>
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────
export default function Landing() {
  const heroRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const heroOpacity = useTransform(scrollYProgress, [0, 0.75], [1, 0]);
  const heroY       = useTransform(scrollYProgress, [0, 0.75], [0, 90]);

  // Smooth scroll to section
  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="bg-[#05070f] text-white overflow-x-hidden selection:bg-indigo-500/30">

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          HERO
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <div ref={heroRef} className="relative h-screen flex flex-col overflow-hidden">
        {/* Three.js neural particles */}
        <div className="absolute inset-0">
          <NeuralCanvas />
        </div>

        {/* AI generated hero background (faint overlay) */}
        <div className="absolute inset-0 opacity-20">
          <LandingImage
            src={`${import.meta.env.BASE_URL}landing/hero.png`}
            alt="Neural wellness graph"
            className="w-full h-full"
            fallback="from-indigo-950 to-[#05070f]"
          />
        </div>

        {/* Gradient fade to sections */}
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[#05070f]" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#05070f]/40 via-transparent to-[#05070f]/40" />

        {/* Navigation */}
        <nav className="relative z-10 flex items-center justify-between px-8 py-6">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-indigo-500 flex items-center justify-center shadow-lg shadow-indigo-500/40">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <span className="text-[17px] font-semibold tracking-tight">Aura</span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm text-white/50">
            {[["crisis", "The Crisis"], ["product", "Product"], ["technology", "Technology"], ["market", "Market"]].map(([id, label]) => (
              <button type="button" key={id} onClick={() => scrollTo(id)} className="hover:text-white transition">
                {label}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <Link to="/login" className="text-sm text-white/50 hover:text-white px-4 py-2 transition">
              Sign in
            </Link>
            <Link to="/setup" className="text-sm bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-lg transition font-medium shadow-lg shadow-indigo-500/20">
              Get started
            </Link>
          </div>
        </nav>

        {/* Hero copy */}
        <motion.div
          style={{ opacity: heroOpacity, y: heroY }}
          className="relative z-10 flex-1 flex flex-col items-center justify-center text-center px-6"
        >
          <AnimatePresence>
            <motion.div
              key="badge"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.2 }}
              className="inline-flex items-center gap-2 border border-indigo-500/30 bg-indigo-500/10 backdrop-blur-sm rounded-full px-4 py-1.5 text-xs text-indigo-300 tracking-[0.12em] uppercase mb-8"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              Semantic Multi-Agent AI Wellness Platform
            </motion.div>

            <motion.h1
              key="h1"
              initial={{ opacity: 0, y: 28 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1.1, delay: 0.38, ease: [0.22, 1, 0.36, 1] }}
              className="text-5xl sm:text-6xl md:text-7xl font-bold leading-[1.04] tracking-tight mb-6 max-w-4xl"
            >
              The mind deserves{" "}
              <span className="bg-gradient-to-r from-indigo-400 via-violet-300 to-emerald-400 bg-clip-text text-transparent">
                a companion
              </span>
              <br />that truly listens.
            </motion.h1>

            <motion.p
              key="sub"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.9, delay: 0.58 }}
              className="text-lg md:text-xl text-white/50 max-w-2xl leading-relaxed mb-10"
            >
              Aura learns your patterns, connects your mood to your habits, and
              shows up as a personalised coach — grounded in your data, not a script.
              Built on a multi-agent semantic graph that understands you deeper over time.
            </motion.p>

            <motion.div
              key="ctas"
              initial={{ opacity: 0, y: 14 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.72 }}
              className="flex flex-col sm:flex-row gap-4 justify-center"
            >
              <Link
                to="/setup"
                className="group inline-flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl px-8 py-4 text-[15px] font-semibold transition-all duration-300 shadow-xl shadow-indigo-500/25"
              >
                Begin your journey
                <ArrowRight className="h-4 w-4 group-hover:translate-x-0.5 transition-transform" />
              </Link>
              <button
                type="button"
                onClick={() => scrollTo("crisis")}
                className="inline-flex items-center justify-center border border-white/12 hover:border-white/25 text-white/60 hover:text-white rounded-xl px-8 py-4 text-[15px] transition-all duration-300 backdrop-blur-sm"
              >
                See the research ↓
              </button>
            </motion.div>
          </AnimatePresence>
        </motion.div>

        {/* Scroll nudge */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.8 }}
          className="relative z-10 flex flex-col items-center gap-1.5 pb-8"
        >
          <motion.div
            animate={{ y: [0, 7, 0] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
            className="w-px h-10 bg-gradient-to-b from-white/20 to-transparent"
          />
        </motion.div>
      </div>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 1 — THE SCALE OF THE CRISIS
          Source: WHO Mental Health Fact Sheet 2025 · McKinsey MHI 2025
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="crisis" className="bg-[#05070f]">
        <Label n="01" tag="The Crisis" />

        <div className="max-w-6xl grid lg:grid-cols-2 gap-16 items-center">
          <div>
            <h2 className="text-4xl md:text-6xl font-bold leading-[1.08] mb-6">
              The largest unaddressed health crisis{" "}
              <span className="text-rose-400">in human history.</span>
            </h2>
            <p className="text-white/50 text-lg leading-relaxed mb-10 max-w-lg">
              Over a billion people are living with a mental health condition right now.
              Most of them — <span className="text-white/80">the vast majority</span> — will never receive
              adequate care. Not because the solutions don't exist. Because no one
              built them at scale.
            </p>

            <div className="grid grid-cols-2 gap-8">
              <Stat value={1} suffix="B+" label="people living with a mental health condition globally" source="WHO, Sept 2025" color="text-rose-400" />
              <Stat value={1} suffix=" in 7" label="people worldwide — not 1 in 100, not 1 in 20" source="WHO Mental Health Atlas 2024" color="text-orange-400" />
              <Stat value={1} suffix="T" prefix="$" label="annual cost in lost productivity from depression & anxiety alone" source="WHO / McKinsey MHI 2025" color="text-yellow-400" />
              <Stat value={4.4} suffix="T" prefix="$" decimals={1} label="GDP unlocked by scaling known mental health interventions" source="McKinsey Health Institute" color="text-emerald-400" />
            </div>
          </div>

          <div className="relative">
            <LandingImage
              src={`${import.meta.env.BASE_URL}landing/crisis.png`}
              alt="Global mental health treatment gap visualized as constellation of dots"
              className="aspect-video w-full"
              fallback="from-rose-900/30 to-orange-900/10"
            />
            <div className="absolute inset-0 rounded-2xl ring-1 ring-white/5" />
            <p className="mt-3 text-xs text-white/20 text-center italic">
              Each dot = a city where mental health care is needed.
              Bright = access. Dim = the treatment gap.
            </p>
          </div>
        </div>

        <div className="mt-16">
          <Quote
            text="The mind is its own place, and in itself can make a heaven of hell, a hell of heaven."
            author="John Milton"
            work="Paradise Lost, 1667"
            accent="rose"
          />
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 2 — WHY CURRENT SOLUTIONS FAIL
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="problem" className="bg-gradient-to-b from-[#05070f] to-[#07091a]">
        <Label n="02" tag="The Failure" />

        <div className="max-w-5xl">
          <h2 className="text-4xl md:text-6xl font-bold leading-[1.08] mb-4">
            96% of wellness app users quit within 15 days.
          </h2>
          <h3 className="text-2xl md:text-3xl text-white/30 font-light mb-14">
            This is not a retention problem. It's a design philosophy problem.
          </h3>

          <div className="grid md:grid-cols-3 gap-6 mb-16">
            {[
              {
                label: "The therapy barrier",
                icon: "🏥",
                points: ["25-day average wait for an appointment", "$200+ per session — inaccessible to most", "Only 1–2% of global health funding goes to mental health"],
                source: "McKinsey MHI 2025 · WHO",
              },
              {
                label: "The app failure",
                icon: "📱",
                points: ["Generic responses — same for everyone", "No memory, no learning, no coaching", "4% still using at day 15 (Deloitte 2024)"],
                source: "Deloitte Mental Health Industry 2024",
              },
              {
                label: "The funding gap",
                icon: "💸",
                points: ["$200B annual mental health financing gap", "67% of budgets locked in institutional care", "Community-based care gets $0.51 per person/year in low-income countries"],
                source: "McKinsey MHI 2025 · WHO Atlas 2024",
              },
            ].map((card, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.7 }}
                className="bg-white/3 border border-white/8 rounded-2xl p-6"
              >
                <span className="text-2xl mb-3 block">{card.icon}</span>
                <h3 className="font-semibold text-white mb-3">{card.label}</h3>
                <ul className="space-y-2.5 mb-4">
                  {card.points.map((p, j) => (
                    <li key={j} className="flex items-start gap-2 text-sm text-white/50">
                      <span className="text-rose-400 mt-0.5 shrink-0">—</span>
                      {p}
                    </li>
                  ))}
                </ul>
                <p className="text-[11px] text-white/20 italic">{card.source}</p>
              </motion.div>
            ))}
          </div>

          <div className="bg-white/3 border border-white/8 rounded-2xl p-8 mb-14">
            <h3 className="text-xs tracking-widest uppercase text-white/25 mb-5">Competitor landscape</h3>
            <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">
              {[
                ["Calm", "Passive content library. No personalization. No learning."],
                ["Headspace", "Meditation library. No coaching. No memory."],
                ["Wysa", "Generic chatbot. Users feel unheard at scale."],
                ["Woebot", "Exited the consumer market entirely in 2025."],
                ["BetterHelp", "$240–360/month. Human bottleneck. Not scalable."],
              ].map(([name, fail], i) => (
                <div key={i} className="border border-white/6 rounded-xl p-4">
                  <p className="text-sm font-medium text-white/60 mb-1">{name}</p>
                  <p className="text-xs text-white/30 leading-relaxed">{fail}</p>
                </div>
              ))}
            </div>
          </div>

          <Quote
            text="The curious paradox is that when I accept myself just as I am, then I can change."
            author="Carl Rogers"
            work="On Becoming a Person, 1961"
            accent="violet"
          />
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 3 — THE USER TRUTH
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="truth" className="bg-[#07091a]">
        <Label n="03" tag="What Users Need" />

        <div className="max-w-4xl">
          <h2 className="text-4xl md:text-5xl font-bold leading-[1.1] mb-4">
            People don't want a wellness app.
          </h2>
          <h2 className="text-4xl md:text-5xl font-bold leading-[1.1] mb-14 text-indigo-400">
            They want to feel known.
          </h2>

          <div className="space-y-8 mb-16">
            {[
              { q: "Feel heard, not processed.", accent: "indigo" as const, attr: "User research" },
              { q: "Give me insights about me — not generic wellness tips that could apply to anyone.", accent: "emerald" as const, attr: "User research" },
              { q: "Help me build habits that actually fit my life. Not a 90-day transformation programme.", accent: "violet" as const, attr: "User research" },
              { q: "Be there in the hard moment. Not just the good days.", accent: "rose" as const, attr: "User research · crisis design principle" },
            ].map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.7 }}
              >
                <Quote text={item.q} author={item.attr} work="" accent={item.accent} />
              </motion.div>
            ))}
          </div>

          <div className="border border-white/10 rounded-2xl p-8 bg-white/2">
            <p className="text-white/30 text-xs uppercase tracking-widest mb-4">The real insight</p>
            <p className="text-xl text-white/80 leading-relaxed">
              The gap isn't technology. It's that no one designed around what users need to{" "}
              <em className="not-italic text-white font-medium">feel</em> — not just what
              they're told they should do.
            </p>
          </div>
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 4 — THE PRODUCT
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="product" className="bg-gradient-to-b from-[#07091a] to-[#080c1e]">
        <Label n="04" tag="The Product" />

        <div className="max-w-6xl">
          <h2 className="text-4xl md:text-6xl font-bold leading-[1.08] mb-4">
            A companion that{" "}
            <span className="bg-gradient-to-r from-indigo-400 to-emerald-400 bg-clip-text text-transparent">
              knows you.
            </span>
          </h2>
          <p className="text-lg text-white/45 mb-14 max-w-xl leading-relaxed">
            Not a chatbot with a wellness skin. A semantic multi-agent system that connects
            your mood, your journals, your habits, and your patterns into one coherent picture
            — and acts on it.
          </p>

          <div className="grid lg:grid-cols-2 gap-12 mb-16 items-start">
            {/* Aura mock conversation */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
              className="bg-white/4 border border-white/10 rounded-2xl p-7"
            >
              <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/8">
                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-400 to-violet-500 flex items-center justify-center text-xs font-bold text-white">A</div>
                <div>
                  <p className="text-sm font-semibold text-white">Aura</p>
                  <p className="text-[11px] text-emerald-400">● Online</p>
                </div>
              </div>
              <div className="space-y-4 text-[14.5px] leading-relaxed text-white/75">
                <p>Good morning, Priya.</p>
                <p>
                  Your mood has been rising this week — up{" "}
                  <span className="text-emerald-400 font-medium">1.8 points</span> from last week.
                  I noticed you exercised 3 days in a row. That's your{" "}
                  <span className="text-emerald-400 font-medium">single strongest mood lever</span>.
                </p>
                <p>
                  Yesterday's journal mentioned{" "}
                  <span className="text-amber-400 font-medium">'deadline pressure'</span> again.
                  That's the <span className="text-amber-400 font-medium">4th time this month</span>.
                  Want to talk about it?
                </p>
              </div>
              <div className="mt-6 pt-4 border-t border-white/8 flex items-center gap-3">
                <div className="flex-1 bg-white/6 rounded-lg px-4 py-2.5 text-sm text-white/30">
                  Share what's on your mind...
                </div>
                <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center shrink-0">
                  <ArrowRight className="h-3.5 w-3.5 text-white" />
                </div>
              </div>
            </motion.div>

            {/* Coach image */}
            <div className="space-y-4">
              <LandingImage
                src={`${import.meta.env.BASE_URL}landing/coach.png`}
                alt="Person using Aura wellness app in morning light"
                className="aspect-[4/3] w-full"
                fallback="from-indigo-900/40 to-violet-900/20"
              />
              <p className="text-xs text-white/20 italic text-center">
                Aura in a morning wellness session
              </p>
            </div>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <Feature i={0} icon={Brain}      title="AI Coach"         body="Streaming, CBT-grounded conversation. Opens with your own data, not a welcome message." />
            <Feature i={1} icon={TrendingUp} title="Mood Analytics"   body="Factor correlation, weekly trends, emotion frequency — all derived from your history." />
            <Feature i={2} icon={Heart}      title="AI Journal"       body="Free-write entries analyzed for themes, sentiment, and non-obvious personal patterns." />
            <Feature i={3} icon={Zap}        title="Wellness Plans"   body="Evidence-based 4-week plans generated from your mood data — CBT and habit-science backed." />
            <Feature i={4} icon={Shield}     title="Crisis Safety"    body="5-level always-on detection. Resources injected inline. Never a redirect, never alarming." />
            <Feature i={5} icon={Sparkles}   title="Streak Engine"    body="Daily habit loop, milestone celebrations, and a personalized daily check-in ritual." />
          </div>
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 5 — THE TECHNOLOGY MOAT
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="technology" className="bg-[#080c1e]">
        <Label n="05" tag="The Moat" />

        <div className="max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-16 items-start mb-16">
            <div>
              <h2 className="text-4xl md:text-5xl font-bold leading-[1.1] mb-4">
                Every other app calls{" "}
                <span className="line-through text-white/20">a single LLM.</span>
              </h2>
              <h2 className="text-4xl md:text-5xl font-bold leading-[1.1] mb-8 text-violet-300">
                Aura runs a semantic multi-agent graph.
              </h2>
              <p className="text-white/50 leading-relaxed mb-8">
                Seven specialised agents reason across your entire wellness picture
                simultaneously. Each one is an expert. Together, they produce insights
                no single call to a language model ever could.
              </p>
              <div className="border border-indigo-500/20 bg-indigo-500/6 rounded-2xl p-6">
                <p className="text-sm font-semibold text-indigo-300 mb-2">The switching cost</p>
                <p className="text-sm text-white/50 leading-relaxed">
                  A user's entire wellness history lives in Aura's semantic graph.
                  It gets smarter every single day they use it. Leaving means losing
                  their personal mental health record — a switching cost no competitor can replicate.
                </p>
              </div>
            </div>

            <LandingImage
              src={`${import.meta.env.BASE_URL}landing/tech.png`}
              alt="Seven AI agent spheres connected by flowing data streams"
              className="aspect-video w-full"
              fallback="from-violet-900/40 to-indigo-900/20"
            />
          </div>

          {/* Agent flow — monospace diagram */}
          <div className="bg-[#05070f] border border-white/8 rounded-2xl p-8 font-mono text-sm overflow-x-auto">
            <p className="text-xs text-white/20 tracking-widest uppercase mb-5">Live agent graph  ·  every message</p>
            {[
              { name: "semantic_router",      time: "<50ms", desc: "Embedding cosine similarity — intent classification, no LLM on hot path", color: "text-indigo-300" },
              { name: "context_loader",       time: "~80ms", desc: "Parallel async DB queries — mood, journal, graph insights, plans", color: "text-violet-300" },
              { name: "wellness_coach",       time: "~900ms", desc: "CBT-grounded empathetic conversation, references your personal data", color: "text-emerald-300" },
              { name: "mood_analyzer",        time: "~700ms", desc: "Factor correlation, trend analysis, quantified mood levers", color: "text-cyan-300" },
              { name: "journal_insights",     time: "~600ms", desc: "NLP theme extraction, sentiment scoring, pattern revelation", color: "text-teal-300" },
              { name: "plan_generator",       time: "~800ms", desc: "4-week evidence-based plans derived from your behavioral data", color: "text-sky-300" },
              { name: "crisis_detector",      time: "always", desc: "5-level conservative safety monitoring — runs on every response", color: "text-rose-300" },
              { name: "response_synthesizer", time: "~10ms", desc: "Final formatting, crisis resource injection, SSE stream dispatch", color: "text-amber-300" },
            ].map((a, i) => (
              <motion.div
                key={a.name}
                initial={{ opacity: 0, x: -12 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.06 }}
                className="flex items-start gap-4 py-3 border-b border-white/4 last:border-0"
              >
                <span className={`w-6 text-white/20 shrink-0`}>{i === 0 ? "→" : "↓"}</span>
                <span className={`w-48 shrink-0 ${a.color}`}>{a.name}</span>
                <span className="w-16 shrink-0 text-white/20">{a.time}</span>
                <span className="text-white/30 text-xs leading-relaxed">{a.desc}</span>
              </motion.div>
            ))}
          </div>

          <div className="mt-12">
            <Quote
              text="The whole is greater than the sum of its parts — but only when the parts communicate."
              author="Aristotle"
              work="Metaphysics (adapted)"
              accent="violet"
            />
          </div>
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 6 — WHY AURA WINS RETENTION
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="retention" className="bg-gradient-to-b from-[#080c1e] to-[#07091a]">
        <Label n="06" tag="Retention" />

        <div className="max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-16 items-start mb-16">
            <div>
              <h2 className="text-4xl md:text-5xl font-bold leading-[1.1] mb-4">
                We designed around the{" "}
                <span className="text-emerald-400">4%</span> who stay.
              </h2>
              <p className="text-white/50 text-lg leading-relaxed mb-10">
                And learned exactly what they had that the 96% who quit did not.
                Four non-negotiable ingredients. Present from Day 1.
              </p>

              <div className="space-y-4">
                {[
                  { n: "01", title: "A reason to return tomorrow", body: "Every session ends with a personalised insight drawn from the user's own data — something they couldn't get anywhere else." },
                  { n: "02", title: "A session under 5 minutes", body: "Clinical research: <10 min sessions have the highest retention. Daily check-in takes 90 seconds. Habit forms before friction kills it." },
                  { n: "03", title: "A streak worth protecting", body: "Milestones at 7, 14, 21, 30, 60, 90 days. The streak is tied to real wellness data — it means something because it measures something real." },
                  { n: "04", title: "A moment that felt human", body: "The coach opens every conversation with 'I noticed…' — an observation from your data. Not a welcome message. Evidence you were heard." },
                ].map((item, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 14 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="flex gap-5 p-5 border border-white/6 rounded-xl bg-white/2 hover:bg-white/4 transition"
                  >
                    <span className="font-mono text-[11px] text-white/20 pt-0.5 shrink-0">{item.n}</span>
                    <div>
                      <h3 className="font-semibold text-white text-[15px] mb-1">{item.title}</h3>
                      <p className="text-sm text-white/45 leading-relaxed">{item.body}</p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>

            <LandingImage
              src={`${import.meta.env.BASE_URL}landing/retention.png`}
              alt="Contrast between generic app abandonment and Aura's warm personalized streak"
              className="aspect-square w-full max-w-md mx-auto"
              fallback="from-emerald-900/30 to-indigo-900/20"
            />
          </div>

          <Quote
            text="We are what we repeatedly do. Excellence, then, is not an act, but a habit."
            author="Aristotle"
            work="Nicomachean Ethics"
            accent="emerald"
          />
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SLIDE 7 — MARKET & BUSINESS
          Source: Deloitte 2024 · McKinsey MHI 2025 · WHO
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <Section id="market" className="bg-[#07091a]">
        <Label n="07" tag="Market" />

        <div className="max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-16 items-start mb-16">
            <div>
              <h2 className="text-4xl md:text-6xl font-bold leading-[1.08] mb-6">
                A{" "}
                <span className="text-amber-400">$448 billion</span>{" "}
                market growing toward{" "}
                <span className="text-emerald-400">$573 billion</span> by 2033.
              </h2>
              <p className="text-white/45 text-lg leading-relaxed mb-10">
                Every employer who funds Aura seats is directly recapturing the
                $1 trillion annual productivity drain. The ROI story sells itself.
              </p>

              <div className="grid grid-cols-2 gap-5">
                <Stat value={448} suffix="B" prefix="$" label="Global mental health market 2024" source="Deloitte / Grand View Research 2024" color="text-amber-400" />
                <Stat value={573} suffix="B" prefix="$" label="Projected market size by 2033" source="Deloitte Mental Wellbeing Industry" color="text-emerald-400" />
                <Stat value={5} label="GDP return per $1 invested in mental health" source="McKinsey Health Institute 2025" color="text-indigo-300" suffix="–6×" />
                <Stat value={200} suffix="B" prefix="$" label="Annual global mental health financing gap" source="McKinsey MHI 2025" color="text-rose-400" />
              </div>
            </div>

            <div className="space-y-4">
              <LandingImage
                src={`${import.meta.env.BASE_URL}landing/market.png`}
                alt="Mental health market growth arc visualization"
                className="aspect-video w-full"
                fallback="from-amber-900/30 to-emerald-900/20"
              />

              <div className="grid grid-cols-2 gap-4">
                <div className="bg-white/3 border border-white/8 rounded-xl p-5">
                  <p className="text-xs text-white/30 mb-2 uppercase tracking-widest">Revenue model</p>
                  <ul className="space-y-1.5 text-sm text-white/55">
                    {["Freemium consumer", "Premium AI coaching", "B2B employer licensing", "Healthcare integration"].map(m => (
                      <li key={m} className="flex items-center gap-2">
                        <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400 shrink-0" />
                        {m}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="bg-white/3 border border-white/8 rounded-xl p-5">
                  <p className="text-xs text-white/30 mb-2 uppercase tracking-widest">Why employers buy</p>
                  <p className="text-sm text-white/55 leading-relaxed">
                    $438B in lost annual productivity from untreated employee depression.
                    Every employer who funds Aura seats captures that return directly.
                  </p>
                  <p className="text-xs text-white/25 italic mt-2">McKinsey MHI 2025</p>
                </div>
              </div>
            </div>
          </div>

          <Quote
            text="An investment in knowledge pays the best interest."
            author="Benjamin Franklin"
            work="Poor Richard's Almanack, 1758"
            accent="amber"
          />
        </div>
      </Section>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          CTA
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <section className="relative min-h-[80vh] flex flex-col items-center justify-center text-center overflow-hidden bg-[#05070f] px-6 py-24">
        <div className="absolute inset-0 opacity-40">
          <NeuralCanvas />
        </div>
        <div className="absolute inset-0 bg-gradient-to-b from-[#05070f] via-transparent to-[#05070f]" />

        <motion.div
          initial={{ opacity: 0, y: 32 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 1, ease: [0.22, 1, 0.36, 1] }}
          className="relative z-10 max-w-2xl"
        >
          <Quote
            text="Knowing yourself is the beginning of all wisdom."
            author="Aristotle"
            work=""
            accent="indigo"
          />

          <h2 className="text-4xl md:text-6xl font-bold mt-14 mb-4">
            Start your wellness journey.
          </h2>
          <p className="text-white/40 text-lg mb-10 max-w-md mx-auto">
            Free to start. No credit card. Your data stays local.
            Built by people who believe mental health care should be personal.
          </p>

          <Link
            to="/setup"
            className="group inline-flex items-center gap-3 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white rounded-2xl px-10 py-5 text-lg font-semibold transition-all duration-300 shadow-2xl shadow-indigo-500/20"
          >
            <Sparkles className="h-5 w-5" />
            Begin with Aura
            <ArrowRight className="h-5 w-5 group-hover:translate-x-0.5 transition-transform" />
          </Link>

          <p className="mt-6 text-white/20 text-sm">
            Already have an account?{" "}
            <Link to="/login" className="text-white/40 hover:text-white transition underline underline-offset-4">
              Sign in
            </Link>
          </p>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 bg-[#03040a] px-8 py-12">
        <div className="max-w-6xl mx-auto">
          {/* Top row */}
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 pb-8 border-b border-white/5">
            {/* Brand */}
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2.5">
                <div className="w-7 h-7 rounded-xl bg-indigo-600 flex items-center justify-center">
                  <Sparkles className="h-3.5 w-3.5 text-white" />
                </div>
                <span className="font-bold text-white/70 text-base tracking-tight">Aura</span>
              </div>
              <p className="text-xs text-white/25 max-w-[220px] leading-relaxed">
                AI-powered mental wellness — your personal companion for mood, growth, and clarity.
              </p>
            </div>

            {/* Features */}
            <div className="flex flex-col gap-1.5">
              <p className="text-[10px] uppercase tracking-widest text-white/20 font-medium mb-1">Technology</p>
              <span className="text-xs text-white/30">Multi-Agent Intelligence</span>
              <span className="text-xs text-white/30">Evidence-based design</span>
              <span className="text-xs text-white/30">Cohen's d = 0.47 coaching effect</span>
            </div>

            {/* Sources */}
            <div className="flex flex-col gap-1.5">
              <p className="text-[10px] uppercase tracking-widest text-white/20 font-medium mb-1">Data Sources</p>
              <span className="text-xs text-white/30">WHO Global Health Report 2025</span>
              <span className="text-xs text-white/30">McKinsey MHI 2025</span>
              <span className="text-xs text-white/30">Deloitte Workplace Study 2024</span>
            </div>
          </div>

          {/* Bottom row */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-6 text-[11px]">
            <span className="text-white/20">© 2025 Aura · AI Mental Wellness Platform</span>
            <span className="text-white/20">
              Built by{' '}
              <a
                href="https://www.linkedin.com/in/bharath-sudarsanam/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-400/70 hover:text-indigo-300 transition-colors underline underline-offset-2"
              >
                Sudarsanam Bharath
              </a>
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
